name: evently_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-162.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.2
  flutter_native_splash: ^2.4.7
  flutter_localizations:
    sdk: flutter
  intl: any
  animated_switch: ^0.0.3
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flutter_screenutil: ^5.9.3
  icons_plus: ^5.0.0
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  
  


flutter_native_splash:
  color: #ffffff"
  fullscreen: true
  image: assets/images/Logo_colum.png

  android_12:
    color: "#ffffff"
    icon_background_color: #ffffff"
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
